/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lsFynTG0GI8
 */
import Link from "next/link"
import { CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function y() {
  return (
    <div className="flex flex-col min-h-[100dvh] dark">
      <header className="px-4 lg:px-6 h-14 flex items-center bg-gradient-to-r from-gray-800 to-gray-900">
        <Link className="flex items-center justify-center" href="#">
          <span className="sr-only text-white">Acme Inc</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4 text-white" href="#">
            Projects
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4 text-white" href="#">
            Skills
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4 text-white" href="#">
            Experience
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4 text-white" href="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="grid gap-12 lg:gap-24 flex-1 bg-gradient-to-b from-gray-700 to-gray-800">
        <section className="grid gap-4 px-4 md:px-6">
          <div className="space-y-4">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl text-white">My Education</h2>
            <p className="max-w-prose text-gray-500 md:text-xl/relaxed dark:text-gray-400 text-white">
              Here are some of the educational experiences I've had. Click on an institution to see more details.
            </p>
          </div>
          <div className="grid gap-6">
            <Card>
              <CardHeader>
                <div className="flex items-center space-x-2">
                  <img
                    alt="University of Web Development"
                    className="rounded-full"
                    height="60"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "60/60",
                      objectFit: "cover",
                    }}
                    width="60"
                  />
                  <div className="space-y-1.5">
                    <h3 className="text-base font-semibold text-white">University of Web Development</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400 text-white">Bachelor's in Web Development</p>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="p-4">
                <img
                  alt="University of Web Development"
                  className="aspect-video overflow-hidden rounded-lg object-cover object-center"
                  height="140"
                  src="/placeholder.svg"
                  width="250"
                />
              </CardContent>
              <CardFooter>
                <Button className="bg-green-500 text-white" size="sm">
                  View Details
                </Button>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <div className="flex items-center space-x-2">
                  <img
                    alt="Coding Academy"
                    className="rounded-full"
                    height="60"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "60/60",
                      objectFit: "cover",
                    }}
                    width="60"
                  />
                  <div className="space-y-1.5">
                    <h3 className="text-base font-semibold text-white">Coding Academy</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400 text-white">
                      Diploma in Advanced Programming
                    </p>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="p-4">
                <img
                  alt="Coding Academy"
                  className="aspect-video overflow-hidden rounded-lg object-cover object-center"
                  height="140"
                  src="/placeholder.svg"
                  width="250"
                />
              </CardContent>
              <CardFooter>
                <Button className="bg-green-500 text-white" size="sm">
                  View Details
                </Button>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <div className="flex items-center space-x-2">
                  <img
                    alt="Tech Institute"
                    className="rounded-full"
                    height="60"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "60/60",
                      objectFit: "cover",
                    }}
                    width="60"
                  />
                  <div className="space-y-1.5">
                    <h3 className="text-base font-semibold text-white">Tech Institute</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400 text-white">Certificate in Web Design</p>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="p-4" />
              <CardFooter>
                <Button className="bg-green-500 text-white" size="sm">
                  View Details
                </Button>
              </CardFooter>
            </Card>
          </div>
        </section>
        <section className="grid gap-4 px-4 md:px-6">
          <div className="space-y-4">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl text-white">My Experience</h2>
            <p className="max-w-prose text-gray-500 md:text-xl/relaxed dark:text-gray-400 text-white">
              Here are my previous work experiences:
            </p>
          </div>
          <div className="grid gap-6">
            <div className="bg-gray-800 p-4 rounded-lg text-white">
              <div className="flex items-center gap-2">
                <img
                  alt="Company Logo"
                  className="rounded-full"
                  height="60"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "60/60",
                    objectFit: "cover",
                  }}
                  width="60"
                />
                <h3 className="text-lg font-bold">Acme Inc</h3>
              </div>
              <p className="text-sm">Frontend Developer (2019-2021)</p>
              <div className="flex items-center gap-2">
                <div>
                  <p className="text-sm">Frontend Developer</p>
                  <p className="text-xs">Responsible for front-end development tasks.</p>
                </div>
              </div>
            </div>
            <div className="bg-gray-800 p-4 rounded-lg text-white">
              <div className="flex items-center gap-2">
                <img
                  alt="Company Logo"
                  className="rounded-full"
                  height="60"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "60/60",
                    objectFit: "cover",
                  }}
                  width="60"
                />
                <h3 className="text-lg font-bold">Example Corp</h3>
              </div>
              <p className="text-sm">Web Designer (2017-2019)</p>
              <div className="flex items-center gap-2">
                <div>
                  <p className="text-sm">Web Designer</p>
                  <p className="text-xs">Responsible for designing web interfaces.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="grid gap-4 px-4 md:px-6">
          <div className="space-y-4">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl text-white">Contact Me</h2>
            <p className="max-w-prose text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400 text-white">
              Interested in working together? Send me a message.
            </p>
          </div>
          <div className="mx-auto w-full max-w-[400px] space-y-4">
            <form className="grid gap-4">
              <div className="grid gap-2">
                <Label className="text-white" htmlFor="name">
                  Name
                </Label>
                <Input id="name" required />
              </div>
              <div className="grid gap-2">
                <Label className="text-white" htmlFor="email">
                  Email
                </Label>
                <Input id="email" required type="email" />
              </div>
              <div className="grid gap-2">
                <Label className="text-white" htmlFor="subject">
                  Subject
                </Label>
                <Input id="subject" required />
              </div>
              <div className="grid gap-2">
                <Label className="text-white" htmlFor="message">
                  Message
                </Label>
                <Textarea id="message" required />
              </div>
              <Button className="bg-blue-500 text-white" type="submit">
                Send
              </Button>
            </form>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t bg-gradient-to-t from-gray-700 to-gray-800">
        <p className="text-xs text-gray-500 dark:text-gray-400 text-white">© 2024 Acme Inc. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4 text-white" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4 text-white" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}